### PR TITLE
Tracing: Add specifications on default TraceParams.

### PR DESCRIPTION
**Pull request by songy23**
Related to https://github.com/census-instrumentation/opencensus-specs/issues/138.

/cc @bogdandrutu

### CODE REVIEW

**Comment by songy23** [comment]
> 128 links sounds very high. what is a use case for tens of links much less over a hundred in the same span?

@bogdandrutu Could you answer this question?

**Comment by bogdandrutu** [comment]
The size of links is small so no memory issue to support 128, but probably the number is too high for real world use-cases.

@songy23 I would reduce that to 32 probably. The reason for this is that if you have some kind of batching you likely have >10 batched operations (not always but sometime).

**Comment by songy23** [comment]
SG, updated the limit on `Link`s to 32. Will update Java default params as well.

**Comment by adriancole** [comment]
thx folks

**Pull request merged**
